### ISSUE TITLE
reducing HTML hard coded efforts 

### ISSUE THREAD

**Issue by swaroopRajwal** [rhvsingh/new-project#17]
We can have an array of objects instead of hardcoding it in `index.html` 
it'll keep the code clean and it'd be easier for you to make any changes in the design 
just change it in one place and it'll be reflected throughout the project 

Can I work on this?

And you've marked #8 as close but the problem still exists 
![image](https://user-images.githubusercontent.com/72123851/193541183-a50d1a0e-94e4-4e43-994b-b9901bd09f62.png)

**Comment by rhvsingh** [comment]
Yeah sure go ahead @swaroopRajwal
