### ISSUE TITLE
change the color of card 

### ISSUE THREAD

**Issue by stutimongia2024** [rhvsingh/new-project#4]

**Comment by kevalvavaliya** [comment]
I want to work on this issue. Kindly assign me the same

**Comment by rhvsingh** [comment]
Sure, you are good to go 👍.

**Comment by AryanKansagara** [comment]
Is anyone working on the issue?

**Comment by kevalvavaliya** [comment]
Yep I am working on the issue

**Comment by AryanKansagara** [comment]
Ok Great Happy Coding !!
